# Generated by Django 4.1.4 on 2023-03-27 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('zip', models.CharField(max_length=20, null=True)),
            ],
            options={
                'unique_together': {('city', 'street')},
            },
        ),
        migrations.CreateModel(
            name='Mediator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=255)),
                ('relevant_experience', models.TextField()),
                ('mediation_areas', models.CharField(choices=[('FA', 'Family'), ('FR', 'Friends'), ('NE', 'Neighbors'), ('ED', 'Education'), ('OR', 'Organizations'), ('BS', 'Buisiness'), ('PO', 'Politics'), ('OT', 'Other')], default='OT', max_length=2)),
                ('certification_course', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='AddressMediator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negoflict_app.address')),
                ('mediator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negoflict_app.mediator')),
            ],
        ),
    ]
