# Generated by Django 4.1.7 on 2023-04-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negoflict_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
