# Generated by Django 4.1.4 on 2022-12-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negoflict_app', '0002_remove_client_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediator',
            options={'ordering': ['user__username']},
        ),
    ]
