# Generated by Django 4.1.7 on 2023-05-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negoflict_app', '0002_alter_address_unique_together_alter_address_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediator',
            name='mediation_areas',
            field=models.CharField(choices=[('FA', 'Family'), ('FR', 'Friends'), ('NE', 'Neighbors'), ('ED', 'Education'), ('OR', 'Organizations'), ('BS', 'Business'), ('PO', 'Politics'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
