# Generated by Django 4.1.7 on 2023-04-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_first_loged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_loged',
            new_name='first_logged',
        ),
    ]
