# Generated by Django 4.1.4 on 2023-01-09 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negoflict_app', '0003_alter_mediator_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('FA', 'Family'), ('FR', 'Friends'), ('NE', 'Neighbors'), ('ED', 'Education'), ('OR', 'Organizations'), ('BS', 'Buisiness'), ('PO', 'Politics'), ('OT', 'Other')], default='OT', max_length=2)),
                ('sub_category', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=180)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('mediator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negoflict_app.mediator')),
            ],
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cteate_at', models.DateTimeField(auto_now=True)),
                ('chat', models.CharField(choices=[('A', 'Chat only with side A'), ('B', 'Chat only with side B'), ('G', 'Chat with the group')], default='G', max_length=1)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.case')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('A', 'Side A'), ('B', 'Side B'), ('N', 'Null')], default='N', max_length=1)),
                ('group_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.groupchat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('blob', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('group_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.groupchat')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.groupmember')),
            ],
        ),
    ]
