# Generated by Django 4.1.7 on 2023-04-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='AgoraUser',
        ),
    ]
