# Generated by Django 4.1.7 on 2023-04-01 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_message_date_time_delete_agorauser'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='case',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='session.case'),
            preserve_default=False,
        ),
    ]
