# Generated by Django 4.1.7 on 2023-03-06 08:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_case_id_agorauser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agorauser',
            name='id',
        ),
        migrations.AddField(
            model_name='agorauser',
            name='chat_user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='agorauser',
            name='nickname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agorauser',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agorauser',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
