# Generated by Django 4.1.7 on 2023-04-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_message_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='case',
        ),
    ]
