# Generated by Django 4.1.7 on 2023-03-06 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '0003_remove_agorauser_id_agorauser_chat_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agorauser',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='session.case'),
        ),
        migrations.AlterField(
            model_name='agorauser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
