# Generated by Django 4.1.7 on 2023-03-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_alter_case_close_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='side',
            field=models.CharField(choices=[('A', 'Side A'), ('B', 'Side B'), ('G', 'Null')], default='G', max_length=1),
        ),
    ]
