# Generated by Django 4.1.7 on 2023-03-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_alter_agorauser_case_alter_agorauser_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agorauser',
            unique_together=set(),
        ),
    ]
