# Generated by Django 4.1.7 on 2023-05-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('FA', 'Family'), ('FR', 'Friends'), ('NE', 'Neighbors'), ('ED', 'Education'), ('OR', 'Organizations'), ('BS', 'Business'), ('PO', 'Politics'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
