# Generated by Django 4.1.7 on 2023-05-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_alter_case_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='group_chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session.groupchat'),
        ),
    ]
