# Generated by Django 4.1.7 on 2023-05-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0011_groupmember_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='case_rate',
            field=models.CharField(choices=[('VS', 'Very satisfied'), ('SS', 'Satisfied'), ('OK', 'OK'), ('DS', 'Disatisfied'), ('VF', 'Very disatisfied')], default='', max_length=2, null=True),
        ),
    ]
